/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'vehicles' : IDL.Null,
  'other' : IDL.Null,
  'home' : IDL.Null,
  'toys' : IDL.Null,
  'furniture' : IDL.Null,
  'books' : IDL.Null,
  'sports' : IDL.Null,
  'fashion' : IDL.Null,
  'electronics' : IDL.Null,
});
export const SortOrder = IDL.Variant({
  'newest' : IDL.Null,
  'priceDesc' : IDL.Null,
  'priceAsc' : IDL.Null,
});
export const ListingStatus = IDL.Variant({
  'sold' : IDL.Null,
  'reserved' : IDL.Null,
  'available' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Media = IDL.Record({
  'hash' : ExternalBlob,
  'mediaType' : IDL.Text,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'currency' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(Media),
});
export const UserProfile = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'username' : IDL.Text,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'longitude' : IDL.Opt(IDL.Float64),
  'currency' : IDL.Text,
  'location' : IDL.Text,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'lastMessageAt' : IDL.Int,
  'listingId' : IDL.Nat,
  'seller' : IDL.Principal,
  'buyer' : IDL.Principal,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'sentAt' : IDL.Int,
  'conversationId' : IDL.Nat,
});
export const OfferStatus = IDL.Variant({
  'pending' : IDL.Null,
  'countered' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'status' : OfferStatus,
  'listingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'counterAmount' : IDL.Opt(IDL.Nat),
  'buyer' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'offerAccepted' : IDL.Null,
  'offerDeclined' : IDL.Null,
  'savedListingSold' : IDL.Null,
  'newOffer' : IDL.Null,
  'savedListingPriceChanged' : IDL.Null,
  'newMessage' : IDL.Null,
  'offerCountered' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : NotificationType,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Nat),
});
export const PublicProfile = IDL.Record({
  'totalRatings' : IDL.Nat,
  'username' : IDL.Text,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'activeListings' : IDL.Nat,
  'avgRating' : IDL.Nat,
});
export const ReportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const ReportTarget = IDL.Variant({
  'listing' : IDL.Nat,
  'user' : IDL.Principal,
  'rating' : IDL.Record({ 'listingId' : IDL.Nat, 'seller' : IDL.Principal }),
});
export const ReportReason = IDL.Variant({
  'other' : IDL.Null,
  'scam' : IDL.Null,
  'spam' : IDL.Null,
  'prohibited' : IDL.Null,
  'offensive' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReportStatus,
  'createdAt' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'target' : ReportTarget,
  'reporter' : IDL.Principal,
  'reason' : ReportReason,
});
export const PublicRating = IDL.Record({
  'review' : IDL.Opt(IDL.Text),
  'listingId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'reviewerUsername' : IDL.Text,
  'stars' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'role' : UserRole,
});
export const OfferResponse = IDL.Variant({
  'accept' : IDL.Null,
  'counter' : IDL.Null,
  'decline' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminRemoveListing' : IDL.Func([IDL.Nat], [], []),
  'adminRemoveRating' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'browseListings' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(Category),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(SortOrder),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Category, IDL.Vec(Media)],
      [Listing],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'dismissReport' : IDL.Func([IDL.Nat], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getMyOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOffersForListing' : IDL.Func([IDL.Nat], [IDL.Vec(Offer)], ['query']),
  'getPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicProfile)],
      ['query'],
    ),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getSavedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getSellerListings' : IDL.Func(
      [IDL.Principal, IDL.Opt(ListingStatus), IDL.Nat, IDL.Nat],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'getSellerReviews' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PublicRating)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'makeOffer' : IDL.Func([IDL.Nat, IDL.Nat], [Offer], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'rateSeller' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'reportListing' : IDL.Func(
      [IDL.Nat, ReportReason, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'reportRating' : IDL.Func(
      [IDL.Principal, IDL.Nat, ReportReason, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'reportUser' : IDL.Func(
      [IDL.Principal, ReportReason, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'respondToOffer' : IDL.Func(
      [IDL.Nat, IDL.Nat, OfferResponse, IDL.Opt(IDL.Nat)],
      [Offer],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Text,
      ],
      [],
      [],
    ),
  'saveListing' : IDL.Func([IDL.Nat], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
  'startConversation' : IDL.Func([IDL.Nat], [Conversation], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unsaveListing' : IDL.Func([IDL.Nat], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        Category,
        IDL.Vec(Media),
        ListingStatus,
      ],
      [Listing],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'vehicles' : IDL.Null,
    'other' : IDL.Null,
    'home' : IDL.Null,
    'toys' : IDL.Null,
    'furniture' : IDL.Null,
    'books' : IDL.Null,
    'sports' : IDL.Null,
    'fashion' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const SortOrder = IDL.Variant({
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  const ListingStatus = IDL.Variant({
    'sold' : IDL.Null,
    'reserved' : IDL.Null,
    'available' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Media = IDL.Record({ 'hash' : ExternalBlob, 'mediaType' : IDL.Text });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'currency' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(Media),
  });
  const UserProfile = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'username' : IDL.Text,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'longitude' : IDL.Opt(IDL.Float64),
    'currency' : IDL.Text,
    'location' : IDL.Text,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'lastMessageAt' : IDL.Int,
    'listingId' : IDL.Nat,
    'seller' : IDL.Principal,
    'buyer' : IDL.Principal,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'sentAt' : IDL.Int,
    'conversationId' : IDL.Nat,
  });
  const OfferStatus = IDL.Variant({
    'pending' : IDL.Null,
    'countered' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'status' : OfferStatus,
    'listingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'counterAmount' : IDL.Opt(IDL.Nat),
    'buyer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'offerAccepted' : IDL.Null,
    'offerDeclined' : IDL.Null,
    'savedListingSold' : IDL.Null,
    'newOffer' : IDL.Null,
    'savedListingPriceChanged' : IDL.Null,
    'newMessage' : IDL.Null,
    'offerCountered' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : NotificationType,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Nat),
  });
  const PublicProfile = IDL.Record({
    'totalRatings' : IDL.Nat,
    'username' : IDL.Text,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'activeListings' : IDL.Nat,
    'avgRating' : IDL.Nat,
  });
  const ReportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const ReportTarget = IDL.Variant({
    'listing' : IDL.Nat,
    'user' : IDL.Principal,
    'rating' : IDL.Record({ 'listingId' : IDL.Nat, 'seller' : IDL.Principal }),
  });
  const ReportReason = IDL.Variant({
    'other' : IDL.Null,
    'scam' : IDL.Null,
    'spam' : IDL.Null,
    'prohibited' : IDL.Null,
    'offensive' : IDL.Null,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReportStatus,
    'createdAt' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'target' : ReportTarget,
    'reporter' : IDL.Principal,
    'reason' : ReportReason,
  });
  const PublicRating = IDL.Record({
    'review' : IDL.Opt(IDL.Text),
    'listingId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'reviewerUsername' : IDL.Text,
    'stars' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  const OfferResponse = IDL.Variant({
    'accept' : IDL.Null,
    'counter' : IDL.Null,
    'decline' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminRemoveListing' : IDL.Func([IDL.Nat], [], []),
    'adminRemoveRating' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'browseListings' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(Category),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(SortOrder),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, Category, IDL.Vec(Media)],
        [Listing],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'dismissReport' : IDL.Func([IDL.Nat], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getMyOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOffersForListing' : IDL.Func([IDL.Nat], [IDL.Vec(Offer)], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getSavedListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getSellerListings' : IDL.Func(
        [IDL.Principal, IDL.Opt(ListingStatus), IDL.Nat, IDL.Nat],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'getSellerReviews' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PublicRating)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'makeOffer' : IDL.Func([IDL.Nat, IDL.Nat], [Offer], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'rateSeller' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'reportListing' : IDL.Func(
        [IDL.Nat, ReportReason, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'reportRating' : IDL.Func(
        [IDL.Principal, IDL.Nat, ReportReason, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'reportUser' : IDL.Func(
        [IDL.Principal, ReportReason, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'respondToOffer' : IDL.Func(
        [IDL.Nat, IDL.Nat, OfferResponse, IDL.Opt(IDL.Nat)],
        [Offer],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Text,
        ],
        [],
        [],
      ),
    'saveListing' : IDL.Func([IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
    'startConversation' : IDL.Func([IDL.Nat], [Conversation], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unsaveListing' : IDL.Func([IDL.Nat], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          Category,
          IDL.Vec(Media),
          ListingStatus,
        ],
        [Listing],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };