/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'vehicles' : null } |
  { 'other' : null } |
  { 'home' : null } |
  { 'toys' : null } |
  { 'furniture' : null } |
  { 'books' : null } |
  { 'sports' : null } |
  { 'fashion' : null } |
  { 'electronics' : null };
export interface Conversation {
  'id' : bigint,
  'lastMessageAt' : bigint,
  'listingId' : bigint,
  'seller' : Principal,
  'buyer' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'seller' : Principal,
  'updatedAt' : bigint,
  'currency' : string,
  'category' : Category,
  'price' : bigint,
  'photos' : Array<Media>,
}
export type ListingStatus = { 'sold' : null } |
  { 'reserved' : null } |
  { 'available' : null };
export interface Media { 'hash' : ExternalBlob, 'mediaType' : string }
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'sentAt' : bigint,
  'conversationId' : bigint,
}
export interface Notification {
  'id' : bigint,
  'notifType' : NotificationType,
  'createdAt' : bigint,
  'read' : boolean,
  'message' : string,
  'relatedId' : [] | [bigint],
}
export type NotificationType = { 'offerAccepted' : null } |
  { 'offerDeclined' : null } |
  { 'savedListingSold' : null } |
  { 'newOffer' : null } |
  { 'savedListingPriceChanged' : null } |
  { 'newMessage' : null } |
  { 'offerCountered' : null };
export interface Offer {
  'id' : bigint,
  'status' : OfferStatus,
  'listingId' : bigint,
  'createdAt' : bigint,
  'counterAmount' : [] | [bigint],
  'buyer' : Principal,
  'amount' : bigint,
}
export type OfferResponse = { 'accept' : null } |
  { 'counter' : null } |
  { 'decline' : null };
export type OfferStatus = { 'pending' : null } |
  { 'countered' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface PublicProfile {
  'totalRatings' : bigint,
  'username' : string,
  'joinDate' : bigint,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'activeListings' : bigint,
  'avgRating' : bigint,
}
export interface PublicRating {
  'review' : [] | [string],
  'listingId' : bigint,
  'createdAt' : bigint,
  'reviewerUsername' : string,
  'stars' : bigint,
  'reviewer' : Principal,
}
export interface Report {
  'id' : bigint,
  'status' : ReportStatus,
  'createdAt' : bigint,
  'description' : [] | [string],
  'target' : ReportTarget,
  'reporter' : Principal,
  'reason' : ReportReason,
}
export type ReportReason = { 'other' : null } |
  { 'scam' : null } |
  { 'spam' : null } |
  { 'prohibited' : null } |
  { 'offensive' : null };
export type ReportStatus = { 'pending' : null } |
  { 'dismissed' : null };
export type ReportTarget = { 'listing' : bigint } |
  { 'user' : Principal } |
  { 'rating' : { 'listingId' : bigint, 'seller' : Principal } };
export type SortOrder = { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null };
export interface UserInfo {
  'principal' : Principal,
  'joinDate' : bigint,
  'name' : string,
  'role' : UserRole,
}
export interface UserProfile {
  'latitude' : [] | [number],
  'username' : string,
  'joinDate' : bigint,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'longitude' : [] | [number],
  'currency' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminRemoveListing' : ActorMethod<[bigint], undefined>,
  'adminRemoveRating' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'browseListings' : ActorMethod<
    [
      [] | [string],
      [] | [Category],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [SortOrder],
      bigint,
      bigint,
    ],
    Array<Listing>
  >,
  'createListing' : ActorMethod<
    [string, string, bigint, string, Category, Array<Media>],
    Listing
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'dismissReport' : ActorMethod<[bigint], undefined>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getBlockedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversations' : ActorMethod<[], Array<Conversation>>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getMessages' : ActorMethod<[bigint], Array<Message>>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'getMyOffers' : ActorMethod<[], Array<Offer>>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getOffersForListing' : ActorMethod<[bigint], Array<Offer>>,
  'getPublicProfile' : ActorMethod<[Principal], [] | [PublicProfile]>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getSavedListings' : ActorMethod<[], Array<Listing>>,
  'getSellerListings' : ActorMethod<
    [Principal, [] | [ListingStatus], bigint, bigint],
    Array<Listing>
  >,
  'getSellerReviews' : ActorMethod<[Principal], Array<PublicRating>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<UserInfo>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'makeOffer' : ActorMethod<[bigint, bigint], Offer>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'rateSeller' : ActorMethod<[bigint, bigint, [] | [string]], undefined>,
  'reportListing' : ActorMethod<
    [bigint, ReportReason, [] | [string]],
    undefined
  >,
  'reportRating' : ActorMethod<
    [Principal, bigint, ReportReason, [] | [string]],
    undefined
  >,
  'reportUser' : ActorMethod<
    [Principal, ReportReason, [] | [string]],
    undefined
  >,
  'respondToOffer' : ActorMethod<
    [bigint, bigint, OfferResponse, [] | [bigint]],
    Offer
  >,
  'saveCallerUserProfile' : ActorMethod<
    [
      string,
      string,
      [] | [ExternalBlob],
      string,
      [] | [number],
      [] | [number],
      string,
    ],
    undefined
  >,
  'saveListing' : ActorMethod<[bigint], undefined>,
  'sendMessage' : ActorMethod<[bigint, string], Message>,
  'startConversation' : ActorMethod<[bigint], Conversation>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unsaveListing' : ActorMethod<[bigint], undefined>,
  'updateListing' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      Category,
      Array<Media>,
      ListingStatus,
    ],
    Listing
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];