/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Conversation {
    id: bigint;
    lastMessageAt: bigint;
    listingId: bigint;
    seller: Principal;
    buyer: Principal;
}
export interface PublicRating {
    review?: string;
    listingId: bigint;
    createdAt: bigint;
    reviewerUsername: string;
    stars: bigint;
    reviewer: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Listing {
    id: bigint;
    status: ListingStatus;
    title: string;
    createdAt: bigint;
    description: string;
    seller: Principal;
    updatedAt: bigint;
    currency: string;
    category: Category;
    price: bigint;
    photos: Array<Media>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Report {
    id: bigint;
    status: ReportStatus;
    createdAt: bigint;
    description?: string;
    target: ReportTarget;
    reporter: Principal;
    reason: ReportReason;
}
export interface UserInfo {
    principal: Principal;
    joinDate: bigint;
    name: string;
    role: UserRole;
}
export interface PublicProfile {
    totalRatings: bigint;
    username: string;
    joinDate: bigint;
    name: string;
    profilePhoto?: ExternalBlob;
    activeListings: bigint;
    avgRating: bigint;
}
export interface Offer {
    id: bigint;
    status: OfferStatus;
    listingId: bigint;
    createdAt: bigint;
    counterAmount?: bigint;
    buyer: Principal;
    amount: bigint;
}
export interface Notification {
    id: bigint;
    notifType: NotificationType;
    createdAt: bigint;
    read: boolean;
    message: string;
    relatedId?: bigint;
}
export interface Message {
    id: bigint;
    content: string;
    sender: Principal;
    sentAt: bigint;
    conversationId: bigint;
}
export type ReportTarget = {
    __kind__: "listing";
    listing: bigint;
} | {
    __kind__: "user";
    user: Principal;
} | {
    __kind__: "rating";
    rating: {
        listingId: bigint;
        seller: Principal;
    };
};
export interface Media {
    hash: ExternalBlob;
    mediaType: string;
}
export interface UserProfile {
    latitude?: number;
    username: string;
    joinDate: bigint;
    name: string;
    profilePhoto?: ExternalBlob;
    longitude?: number;
    currency: string;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    vehicles = "vehicles",
    other = "other",
    home = "home",
    toys = "toys",
    furniture = "furniture",
    books = "books",
    sports = "sports",
    fashion = "fashion",
    electronics = "electronics"
}
export enum ListingStatus {
    sold = "sold",
    reserved = "reserved",
    available = "available"
}
export enum NotificationType {
    offerAccepted = "offerAccepted",
    offerDeclined = "offerDeclined",
    savedListingSold = "savedListingSold",
    newOffer = "newOffer",
    savedListingPriceChanged = "savedListingPriceChanged",
    newMessage = "newMessage",
    offerCountered = "offerCountered"
}
export enum OfferResponse {
    accept = "accept",
    counter = "counter",
    decline = "decline"
}
export enum OfferStatus {
    pending = "pending",
    countered = "countered",
    accepted = "accepted",
    declined = "declined"
}
export enum ReportReason {
    other = "other",
    scam = "scam",
    spam = "spam",
    prohibited = "prohibited",
    offensive = "offensive"
}
export enum ReportStatus {
    pending = "pending",
    dismissed = "dismissed"
}
export enum SortOrder {
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminRemoveListing(listingId: bigint): Promise<void>;
    adminRemoveRating(seller: Principal, listingId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(user: Principal): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    browseListings(keyword: string | null, category: Category | null, minPrice: bigint | null, maxPrice: bigint | null, priceCurrency: string | null, sort: SortOrder | null, offset: bigint, limit: bigint): Promise<Array<Listing>>;
    createListing(title: string, description: string, price: bigint, currency: string, category: Category, photos: Array<Media>): Promise<Listing>;
    deleteListing(id: bigint): Promise<void>;
    dismissReport(reportId: bigint): Promise<void>;
    getAllListings(): Promise<Array<Listing>>;
    getBlockedUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversations(): Promise<Array<Conversation>>;
    getListing(id: bigint): Promise<Listing | null>;
    getMessages(conversationId: bigint): Promise<Array<Message>>;
    getMyListings(): Promise<Array<Listing>>;
    getMyOffers(): Promise<Array<Offer>>;
    getMyRole(): Promise<UserRole>;
    getNotifications(): Promise<Array<Notification>>;
    getOffersForListing(listingId: bigint): Promise<Array<Offer>>;
    getPublicProfile(user: Principal): Promise<PublicProfile | null>;
    getReports(): Promise<Array<Report>>;
    getSavedListings(): Promise<Array<Listing>>;
    getSellerListings(seller: Principal, status: ListingStatus | null, offset: bigint, limit: bigint): Promise<Array<Listing>>;
    getSellerReviews(seller: Principal): Promise<Array<PublicRating>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<UserInfo>>;
    isCallerAdmin(): Promise<boolean>;
    isUsernameAvailable(username: string): Promise<boolean>;
    makeOffer(listingId: bigint, amount: bigint): Promise<Offer>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notifId: bigint): Promise<void>;
    rateSeller(listingId: bigint, stars: bigint, review: string | null): Promise<void>;
    reportListing(listingId: bigint, reason: ReportReason, description: string | null): Promise<void>;
    reportRating(seller: Principal, listingId: bigint, reason: ReportReason, description: string | null): Promise<void>;
    reportUser(user: Principal, reason: ReportReason, description: string | null): Promise<void>;
    respondToOffer(offerId: bigint, listingId: bigint, response: OfferResponse, counterAmount: bigint | null): Promise<Offer>;
    saveCallerUserProfile(name: string, username: string, profilePhoto: ExternalBlob | null, location: string, latitude: number | null, longitude: number | null, currency: string): Promise<void>;
    saveListing(listingId: bigint): Promise<void>;
    sendMessage(conversationId: bigint, content: string): Promise<Message>;
    startConversation(listingId: bigint): Promise<Conversation>;
    unbanUser(user: Principal): Promise<void>;
    unblockUser(user: Principal): Promise<void>;
    unsaveListing(listingId: bigint): Promise<void>;
    updateListing(id: bigint, title: string, description: string, price: bigint, currency: string, category: Category, photos: Array<Media>, status: ListingStatus): Promise<Listing>;
}
import type { Category as _Category, ExternalBlob as _ExternalBlob, Listing as _Listing, ListingStatus as _ListingStatus, Media as _Media, Notification as _Notification, NotificationType as _NotificationType, Offer as _Offer, OfferResponse as _OfferResponse, OfferStatus as _OfferStatus, PublicProfile as _PublicProfile, PublicRating as _PublicRating, Report as _Report, ReportReason as _ReportReason, ReportStatus as _ReportStatus, ReportTarget as _ReportTarget, SortOrder as _SortOrder, UserInfo as _UserInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminRemoveListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveListing(arg0);
            return result;
        }
    }
    async adminRemoveRating(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveRating(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveRating(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async browseListings(arg0: string | null, arg1: Category | null, arg2: bigint | null, arg3: bigint | null, arg4: string | null, arg5: SortOrder | null, arg6: bigint, arg7: bigint): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseListings(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseListings(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Category, arg5: Array<Media>): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, arg3, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg4), await to_candid_vec_n29(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Listing_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, arg3, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg4), await to_candid_vec_n29(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Listing_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async dismissReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReport(arg0);
            return result;
        }
    }
    async getAllListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getListing(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getMyListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOffers(): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOffers();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOffers();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOffersForListing(arg0: bigint): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOffersForListing(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOffersForListing(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfile(arg0: Principal): Promise<PublicProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerListings(arg0: Principal, arg1: ListingStatus | null, arg2: bigint, arg3: bigint): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerListings(arg0, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerListings(arg0, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSellerReviews(arg0: Principal): Promise<Array<PublicRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSellerReviews(arg0);
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSellerReviews(arg0);
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUsernameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameAvailable(arg0);
            return result;
        }
    }
    async makeOffer(arg0: bigint, arg1: bigint): Promise<Offer> {
        if (this.processError) {
            try {
                const result = await this.actor.makeOffer(arg0, arg1);
                return from_candid_Offer_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeOffer(arg0, arg1);
            return from_candid_Offer_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async rateSeller(arg0: bigint, arg1: bigint, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateSeller(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateSeller(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async reportListing(arg0: bigint, arg1: ReportReason, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportListing(arg0, to_candid_ReportReason_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportListing(arg0, to_candid_ReportReason_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async reportRating(arg0: Principal, arg1: bigint, arg2: ReportReason, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportRating(arg0, arg1, to_candid_ReportReason_n73(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportRating(arg0, arg1, to_candid_ReportReason_n73(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async reportUser(arg0: Principal, arg1: ReportReason, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0, to_candid_ReportReason_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0, to_candid_ReportReason_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async respondToOffer(arg0: bigint, arg1: bigint, arg2: OfferResponse, arg3: bigint | null): Promise<Offer> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToOffer(arg0, arg1, to_candid_OfferResponse_n75(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Offer_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToOffer(arg0, arg1, to_candid_OfferResponse_n75(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Offer_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: ExternalBlob | null, arg3: string, arg4: number | null, arg5: number | null, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, await to_candid_opt_n77(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n78(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, await to_candid_opt_n77(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n78(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async saveListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveListing(arg0);
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async startConversation(arg0: bigint): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.startConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startConversation(arg0);
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async unsaveListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveListing(arg0);
            return result;
        }
    }
    async updateListing(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: Category, arg6: Array<Media>, arg7: ListingStatus): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg5), await to_candid_vec_n29(this._uploadFile, this._downloadFile, arg6), to_candid_ListingStatus_n65(this._uploadFile, this._downloadFile, arg7));
                return from_candid_Listing_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, to_candid_Category_n12(this._uploadFile, this._downloadFile, arg5), await to_candid_vec_n29(this._uploadFile, this._downloadFile, arg6), to_candid_ListingStatus_n65(this._uploadFile, this._downloadFile, arg7));
            return from_candid_Listing_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Listing_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Promise<Listing> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Media_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Promise<Media> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_OfferStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferStatus): OfferStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Offer_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Offer): Offer {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_PublicProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicProfile): Promise<PublicProfile> {
    return await from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_PublicRating_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicRating): PublicRating {
    return from_candid_record_n69(_uploadFile, _downloadFile, value);
}
function from_candid_ReportReason_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportReason): ReportReason {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_ReportTarget_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportTarget): ReportTarget {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Promise<Listing | null> {
    return value.length === 0 ? null : await from_candid_Listing_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicProfile]): Promise<PublicProfile | null> {
    return value.length === 0 ? null : await from_candid_PublicProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ListingStatus;
    title: string;
    createdAt: bigint;
    description: string;
    seller: Principal;
    updatedAt: bigint;
    currency: string;
    category: _Category;
    price: bigint;
    photos: Array<_Media>;
}): Promise<{
    id: bigint;
    status: ListingStatus;
    title: string;
    createdAt: bigint;
    description: string;
    seller: Principal;
    updatedAt: bigint;
    currency: string;
    category: Category;
    price: bigint;
    photos: Array<Media>;
}> {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        seller: value.seller,
        updatedAt: value.updatedAt,
        currency: value.currency,
        category: from_candid_Category_n23(_uploadFile, _downloadFile, value.category),
        price: value.price,
        photos: await from_candid_vec_n25(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hash: _ExternalBlob;
    mediaType: string;
}): Promise<{
    hash: ExternalBlob;
    mediaType: string;
}> {
    return {
        hash: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.hash),
        mediaType: value.mediaType
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: [] | [number];
    username: string;
    joinDate: bigint;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    longitude: [] | [number];
    currency: string;
    location: string;
}): Promise<{
    latitude?: number;
    username: string;
    joinDate: bigint;
    name: string;
    profilePhoto?: ExternalBlob;
    longitude?: number;
    currency: string;
    location: string;
}> {
    return {
        latitude: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.latitude)),
        username: value.username,
        joinDate: value.joinDate,
        name: value.name,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.profilePhoto)),
        longitude: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.longitude)),
        currency: value.currency,
        location: value.location
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OfferStatus;
    listingId: bigint;
    createdAt: bigint;
    counterAmount: [] | [bigint];
    buyer: Principal;
    amount: bigint;
}): {
    id: bigint;
    status: OfferStatus;
    listingId: bigint;
    createdAt: bigint;
    counterAmount?: bigint;
    buyer: Principal;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OfferStatus_n44(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        createdAt: value.createdAt,
        counterAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.counterAmount)),
        buyer: value.buyer,
        amount: value.amount
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notifType: _NotificationType;
    createdAt: bigint;
    read: boolean;
    message: string;
    relatedId: [] | [bigint];
}): {
    id: bigint;
    notifType: NotificationType;
    createdAt: bigint;
    read: boolean;
    message: string;
    relatedId?: bigint;
} {
    return {
        id: value.id,
        notifType: from_candid_NotificationType_n49(_uploadFile, _downloadFile, value.notifType),
        createdAt: value.createdAt,
        read: value.read,
        message: value.message,
        relatedId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.relatedId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalRatings: bigint;
    username: string;
    joinDate: bigint;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    activeListings: bigint;
    avgRating: bigint;
}): Promise<{
    totalRatings: bigint;
    username: string;
    joinDate: bigint;
    name: string;
    profilePhoto?: ExternalBlob;
    activeListings: bigint;
    avgRating: bigint;
}> {
    return {
        totalRatings: value.totalRatings,
        username: value.username,
        joinDate: value.joinDate,
        name: value.name,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.profilePhoto)),
        activeListings: value.activeListings,
        avgRating: value.avgRating
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReportStatus;
    createdAt: bigint;
    description: [] | [string];
    target: _ReportTarget;
    reporter: Principal;
    reason: _ReportReason;
}): {
    id: bigint;
    status: ReportStatus;
    createdAt: bigint;
    description?: string;
    target: ReportTarget;
    reporter: Principal;
    reason: ReportReason;
} {
    return {
        id: value.id,
        status: from_candid_ReportStatus_n57(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        description: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.description)),
        target: from_candid_ReportTarget_n60(_uploadFile, _downloadFile, value.target),
        reporter: value.reporter,
        reason: from_candid_ReportReason_n62(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    review: [] | [string];
    listingId: bigint;
    createdAt: bigint;
    reviewerUsername: string;
    stars: bigint;
    reviewer: Principal;
}): {
    review?: string;
    listingId: bigint;
    createdAt: bigint;
    reviewerUsername: string;
    stars: bigint;
    reviewer: Principal;
} {
    return {
        review: record_opt_to_undefined(from_candid_opt_n59(_uploadFile, _downloadFile, value.review)),
        listingId: value.listingId,
        createdAt: value.createdAt,
        reviewerUsername: value.reviewerUsername,
        stars: value.stars,
        reviewer: value.reviewer
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    joinDate: bigint;
    name: string;
    role: _UserRole;
}): {
    principal: Principal;
    joinDate: bigint;
    name: string;
    role: UserRole;
} {
    return {
        principal: value.principal,
        joinDate: value.joinDate,
        name: value.name,
        role: from_candid_UserRole_n38(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    reserved: null;
} | {
    available: null;
}): ListingStatus {
    return "sold" in value ? ListingStatus.sold : "reserved" in value ? ListingStatus.reserved : "available" in value ? ListingStatus.available : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicles: null;
} | {
    other: null;
} | {
    home: null;
} | {
    toys: null;
} | {
    furniture: null;
} | {
    books: null;
} | {
    sports: null;
} | {
    fashion: null;
} | {
    electronics: null;
}): Category {
    return "vehicles" in value ? Category.vehicles : "other" in value ? Category.other : "home" in value ? Category.home : "toys" in value ? Category.toys : "furniture" in value ? Category.furniture : "books" in value ? Category.books : "sports" in value ? Category.sports : "fashion" in value ? Category.fashion : "electronics" in value ? Category.electronics : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    countered: null;
} | {
    accepted: null;
} | {
    declined: null;
}): OfferStatus {
    return "pending" in value ? OfferStatus.pending : "countered" in value ? OfferStatus.countered : "accepted" in value ? OfferStatus.accepted : "declined" in value ? OfferStatus.declined : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offerAccepted: null;
} | {
    offerDeclined: null;
} | {
    savedListingSold: null;
} | {
    newOffer: null;
} | {
    savedListingPriceChanged: null;
} | {
    newMessage: null;
} | {
    offerCountered: null;
}): NotificationType {
    return "offerAccepted" in value ? NotificationType.offerAccepted : "offerDeclined" in value ? NotificationType.offerDeclined : "savedListingSold" in value ? NotificationType.savedListingSold : "newOffer" in value ? NotificationType.newOffer : "savedListingPriceChanged" in value ? NotificationType.savedListingPriceChanged : "newMessage" in value ? NotificationType.newMessage : "offerCountered" in value ? NotificationType.offerCountered : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    dismissed: null;
}): ReportStatus {
    return "pending" in value ? ReportStatus.pending : "dismissed" in value ? ReportStatus.dismissed : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listing: bigint;
} | {
    user: Principal;
} | {
    rating: {
        listingId: bigint;
        seller: Principal;
    };
}): {
    __kind__: "listing";
    listing: bigint;
} | {
    __kind__: "user";
    user: Principal;
} | {
    __kind__: "rating";
    rating: {
        listingId: bigint;
        seller: Principal;
    };
} {
    return "listing" in value ? {
        __kind__: "listing",
        listing: value.listing
    } : "user" in value ? {
        __kind__: "user",
        user: value.user
    } : "rating" in value ? {
        __kind__: "rating",
        rating: value.rating
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    scam: null;
} | {
    spam: null;
} | {
    prohibited: null;
} | {
    offensive: null;
}): ReportReason {
    return "other" in value ? ReportReason.other : "scam" in value ? ReportReason.scam : "spam" in value ? ReportReason.spam : "prohibited" in value ? ReportReason.prohibited : "offensive" in value ? ReportReason.offensive : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Promise<Array<Listing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Listing_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Media>): Promise<Array<Media>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Media_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Offer>): Array<Offer> {
    return value.map((x)=>from_candid_Offer_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n55(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicRating>): Array<PublicRating> {
    return value.map((x)=>from_candid_PublicRating_n68(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserInfo>): Array<UserInfo> {
    return value.map((x)=>from_candid_UserInfo_n71(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ListingStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
async function to_candid_Media_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Media): Promise<_Media> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_OfferResponse_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferResponse): _OfferResponse {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_ReportReason_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportReason): _ReportReason {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_SortOrder_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): _SortOrder {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder | null): [] | [_SortOrder] {
    return value === null ? candid_none() : candid_some(to_candid_SortOrder_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus | null): [] | [_ListingStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ListingStatus_n65(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hash: ExternalBlob;
    mediaType: string;
}): Promise<{
    hash: _ExternalBlob;
    mediaType: string;
}> {
    return {
        hash: await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.hash),
        mediaType: value.mediaType
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    vehicles: null;
} | {
    other: null;
} | {
    home: null;
} | {
    toys: null;
} | {
    furniture: null;
} | {
    books: null;
} | {
    sports: null;
} | {
    fashion: null;
} | {
    electronics: null;
} {
    return value == Category.vehicles ? {
        vehicles: null
    } : value == Category.other ? {
        other: null
    } : value == Category.home ? {
        home: null
    } : value == Category.toys ? {
        toys: null
    } : value == Category.furniture ? {
        furniture: null
    } : value == Category.books ? {
        books: null
    } : value == Category.sports ? {
        sports: null
    } : value == Category.fashion ? {
        fashion: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOrder): {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} {
    return value == SortOrder.newest ? {
        newest: null
    } : value == SortOrder.priceDesc ? {
        priceDesc: null
    } : value == SortOrder.priceAsc ? {
        priceAsc: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    sold: null;
} | {
    reserved: null;
} | {
    available: null;
} {
    return value == ListingStatus.sold ? {
        sold: null
    } : value == ListingStatus.reserved ? {
        reserved: null
    } : value == ListingStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportReason): {
    other: null;
} | {
    scam: null;
} | {
    spam: null;
} | {
    prohibited: null;
} | {
    offensive: null;
} {
    return value == ReportReason.other ? {
        other: null
    } : value == ReportReason.scam ? {
        scam: null
    } : value == ReportReason.spam ? {
        spam: null
    } : value == ReportReason.prohibited ? {
        prohibited: null
    } : value == ReportReason.offensive ? {
        offensive: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferResponse): {
    accept: null;
} | {
    counter: null;
} | {
    decline: null;
} {
    return value == OfferResponse.accept ? {
        accept: null
    } : value == OfferResponse.counter ? {
        counter: null
    } : value == OfferResponse.decline ? {
        decline: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Media>): Promise<Array<_Media>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Media_n30(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
